import type { Metadata } from 'next';
import { NextIntlClientProvider, useMessages } from 'next-intl';

import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Genshin Handbook',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children,
  params: { locale }
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = useMessages();
  return (
    <html lang={locale} suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
